name: medbridge_business
description: Demonstrates how to use the firebase_messaging plugin.

dependencies:
  firebase_analytics: ^5.0.2
  flutter:
    sdk: flutter
  firebase_messaging: ^6.0.13
  firebase_core: ^0.4.0
  shared_preferences: ^0.5.6+1
  google_sign_in: ^4.2.0

dev_dependencies:
  pedantic: ^1.8.0
  flutter_test:
    sdk: flutter
  e2e: ^0.2.1
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true
  assets:
    - images/
