const String TOTAL_PATIENTS = 'TOTAL PATIENTS';
const String TREATMENTS_ONGOING = 'TREATMENTS ONGOING';
const String TREATMENTS_COMPLETED = 'TREATMENTS COMPLETED';
const String REWARD_DUE = 'REWARD DUE';
const String REWARD_COLLECTED = 'REWARD COLLECTED';
const String ADD_NEW_PATIENT = 'Add New Patient';
